server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: dumbledog129:8848
        namespace: 84866ee7-93e8-4f17-a837-aeafc35f16e9
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dumbledog129:3306/seata_account
    username: root
    password: 12345678

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml


