server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
      routes:
        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**
            - After=2022-04-06T23:56:26.291+08:00[Asia/Shanghai]
        - id: payment_routh
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: false
      defaultZone: http://eureka7001.com:7001/eureka/