server:
  port: 2001



spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: my_test_tx_group
#        service:
#          # 事务组对应的集群民称
#          vgroup-mapping.my_test_tx_group: lqx_tx_group
#          # seata-server的地址
#          grouplist.seata-server: dumbledog129:8091
    nacos:
      discovery:
        server-addr: dumbledog129:8848
        namespace: 84866ee7-93e8-4f17-a837-aeafc35f16e9
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://dumbledog129:3306/seata_order
    username: root
    password: 12345678

#seata:
#  enabled: true
#  application-id: ${spring.application.name}
#  tx-service-group: my_test_tx_group
#  config:
#    type: nacos
#    nacos:
#      server-addr: dumbledog129:8848
#      namespace: 84866ee7-93e8-4f17-a837-aeafc35f16e9
#      group: SEATA_GROUP
#      username: "nacos"
#      password: "nacos"
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: dumbledog129:8848
#      namespace: 84866ee7-93e8-4f17-a837-aeafc35f16e9
#      group: SEATA_GROUP
#      username: "nacos"
#      password: "nacos"


feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
